AWSTemplateFormatVersion: 2010-09-09
Description: Application workload template - deploys an autoscaling group that registered with the load balancer from the application VPC template.

Parameters:
  ApplicationName:
    Type: String
    Description: Name of this application
 
Outputs:
  ExampleOutput:
    Description: Example description
    Value: !Ref example.value

Resources:
# autoscaling group
  # register with nlb
# instance type: t3.nano
  # imdsv2
  # userdata: install httpd and write simple web page with instance id from instance metadata
# tag everything with the application name