AWSTemplateFormatVersion: 2010-09-09
Description: Application VPC base template - deploys the VPC, subnets, NLB and registers the PrivateLink service.

Parameters:
  ApplicationName:
    Type: String
    Description: Name of this application
  PrivateLinkPrincipals:
    Type: String
    Description: Account and role in ingress account who are allowed to connect to this endpoint - see README
 
Outputs:
  VPCId:
    Description: Application VPC id
    Value: !Ref ApplicationVPC
    Export:
      Name: !Sub '${ApplicationName}-VPCId'
  NLBTargetGroupARN:
    Description: Application NLB TargetGroup ARN
    Value: !Ref NLBTargetGroup
    Export:
      Name: !Sub '${ApplicationName}-NLBTargetGroupARN'
  NLBSecurityGroupId:
    Description: Application NLB security group id
    Value: !Ref NLBSecurityGroup
    Export:
      Name: !Sub '${ApplicationName}-NLBSGId'
  ApplicationSubnetOne:
    Description: Application subnet one id
    Value: !Ref ApplicationSubnetOne
    Export:
      Name: !Sub '${ApplicationName}-ApplicationSubnetOneId'
  ApplicationSubnetTwo:
    Description: Application subnet two id
    Value: !Ref ApplicationSubnetTwo
    Export:
      Name: !Sub '${ApplicationName}-ApplicationSubnetTwoId'
  ServiceEndpointName:
    Description: PrivateLink endpoint name
    Value: !Sub 'com.amazonaws.vpce.${AWS::Region}.${PrivateLinkService}'

Resources:
  ApplicationVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.250.0.0/22
      EnableDnsSupport: True
      EnableDnsHostnames: True
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Sub '${ApplicationName}-VPC'

  LoadBalancerSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ApplicationVPC
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: 10.250.0.0/24
      Tags:
      - Key: Name
        Value: !Sub '${ApplicationName}-LoadBalancerSubnetOne'

  LoadBalancerSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ApplicationVPC
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: 10.250.1.0/24
      Tags:
      - Key: Name
        Value: !Sub '${ApplicationName}-LoadBalancerSubnetTwo'

  ApplicationSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ApplicationVPC
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: 10.250.2.0/24
      Tags:
      - Key: Name
        Value: !Sub '${ApplicationName}-ApplicationSubnetOne'

  ApplicationSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ApplicationVPC
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: 10.250.3.0/24
      Tags:
      - Key: Name
        Value: !Sub '${ApplicationName}-ApplicationSubnetTwo'

  NLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref ApplicationName
      Type: network
      Scheme: internal
      IpAddressType: ipv4
      SecurityGroups:
      - !Ref NLBSecurityGroup
      Subnets:
      - !Ref LoadBalancerSubnetOne
      - !Ref LoadBalancerSubnetTwo
      Tags:
      - Key: Name
        Value: !Ref ApplicationName

  NLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NLB
      Port: 80
      Protocol: TCP
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref NLBTargetGroup

  NLBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Ref ApplicationName
      VpcId: !Ref ApplicationVPC
      IpAddressType: ipv4
      Port: 80
      Protocol: TCP
      TargetType: instance
      Tags:
      - Key: Name
        Value: !Ref ApplicationName

  NLBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub 'Enable access to ${ApplicationName} EC2 instance'
      VpcId: !Ref ApplicationVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'
      Tags:
      - Key: Name
        Value: !Sub '${ApplicationName}-NLB'

  PrivateLinkService:
    Type: AWS::EC2::VPCEndpointService
    Properties:
      AcceptanceRequired: True
      NetworkLoadBalancerArns:
      - !Ref NLB

  PrivateLinkServicePermissions:
    Type: AWS::EC2::VPCEndpointServicePermissions
    Properties:
      ServiceId: !Ref PrivateLinkService
      AllowedPrincipals:
      - !Ref PrivateLinkPrincipals 